const {_electron:electron}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {messages}=require('../src/reminder-copy.cjs');
const root=path.resolve(__dirname,'..'),data=path.join(root,'_work','reminder-ui-'+Date.now()),output=path.join(root,'outputs/verification');
const env={...process.env,WEEKLIGHT_DATA_DIR:data};delete env.ELECTRON_RUN_AS_NODE;
const launch=()=>electron.launch(process.env.WEEKLIGHT_EXECUTABLE?{executablePath:path.resolve(process.env.WEEKLIGHT_EXECUTABLE),args:[],env}:{args:[root],env});
const checks=[],errors=[];
const state=page=>page.evaluate(()=>window.weeklight.get());
async function captureNotifications(app){await app.evaluate(({Notification})=>{globalThis.__reminderNotifications=[];Notification.isSupported=()=>true;Notification.prototype.show=function(){globalThis.__reminderNotifications.push({title:this.title,body:this.body});};});}
async function popupPage(app){const end=Date.now()+12000;while(Date.now()<end){const p=app.windows().find(w=>w.url().endsWith('/reminder.html'));if(p){p.on('pageerror',e=>errors.push(e.message));await p.waitForSelector('#quote-text[data-id]');return p;}await new Promise(r=>setTimeout(r,50));}throw new Error('Reminder popup missing');}
async function matchesQuote(p,s){await p.waitForFunction(id=>document.querySelector('#quote-text').dataset.id===id,s.reminderMessage.id);assert.equal(await p.locator('#quote-text').innerText(),s.reminderMessage.text);assert.match(await p.locator('#quote-count').innerText(),/^120 /);}
(async()=>{let app;try{
await fs.mkdir(output,{recursive:true});app=await launch();let main=await app.firstWindow();await main.waitForSelector('.month-grid');main.on('pageerror',e=>errors.push(e.message));await captureNotifications(app);
await main.evaluate(()=>window.weeklight.testReminder());let popup=await popupPage(app);let s=await state(main);await matchesQuote(popup,s);
let notifications=await app.evaluate(()=>globalThis.__reminderNotifications);assert.equal(notifications.length,1);assert(notifications[0].body.includes(s.reminderMessage.text));checks.push('test popup and Windows notification use the same catalog message');
const first=s.reminderMessage.id;const previousTasks=JSON.stringify(s.tasks),previousHistory=JSON.stringify(s.history);
await popup.locator('#quote-next').click();await popup.waitForFunction(id=>document.querySelector('#quote-text').dataset.id!==id,first);s=await state(main);assert.notEqual(s.reminderMessage.id,first);assert.equal(JSON.stringify(s.tasks),previousTasks);assert.equal(JSON.stringify(s.history),previousHistory);assert.equal((await app.evaluate(()=>globalThis.__reminderNotifications)).length,1);checks.push('next message changes only copy and does not send another notification');
const beforeTest=s.reminderMessage.id;await main.evaluate(()=>window.weeklight.testReminder());s=await state(main);await matchesQuote(popup,s);assert.notEqual(s.reminderMessage.id,beforeTest);assert.equal((await app.evaluate(()=>globalThis.__reminderNotifications)).length,2);checks.push('an already open popup updates on the next reminder');
const seen=[...s.settings.reminderRotation.seen],current=s.reminderMessage.id;await app.close();app=null;
app=await launch();main=await app.firstWindow();await main.waitForSelector('.month-grid');main.on('pageerror',e=>errors.push(e.message));await captureNotifications(app);s=await state(main);assert.deepEqual(s.settings.reminderRotation.seen,seen);assert.equal(s.reminderMessage.id,current);
await main.evaluate(()=>window.weeklight.testReminder());popup=await popupPage(app);s=await state(main);await matchesQuote(popup,s);assert(!seen.includes(s.reminderMessage.id));checks.push('restarting continues the saved rotation instead of repeating a used message');
const now=new Date();const date=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');
for(const title of ['阅读十页，记下一个新发现','散步片刻，看看窗外的风景','整理今天的小收获'])await main.evaluate(task=>window.weeklight.saveTask(task,1),{title,date,time:'00:00',duration:30,category:'study',reminder:0});
await popup.waitForFunction(()=>document.querySelectorAll('.reminder-row').length===3,null,{timeout:15000});s=await state(main);await matchesQuote(popup,s);notifications=await app.evaluate(()=>globalThis.__reminderNotifications);assert(notifications.at(-1).body.includes(s.reminderMessage.text));assert(s.tasks.every(t=>t.notifiedAt));checks.push('real due reminders preserve task details and share the displayed encouragement with notifications');
await popup.screenshot({path:path.join(output,'reminder-positive.png')});
const popupWindow=await app.browserWindow(popup);await popupWindow.evaluate(w=>w.setSize(400,440));await popup.waitForTimeout(100);const geometry=await popup.evaluate(()=>{const q=document.querySelector('.reminder-quote').getBoundingClientRect(),list=document.querySelector('#reminders').getBoundingClientRect(),foot=document.querySelector('.reminder-footer').getBoundingClientRect();return {quoteBottom:q.bottom,listHeight:list.height,footerBottom:foot.bottom,height:innerHeight,bodyOverflow:document.documentElement.scrollWidth>innerWidth};});assert(geometry.listHeight>60);assert(geometry.footerBottom<=geometry.height);assert.equal(geometry.bodyOverflow,false);checks.push('minimum popup size keeps copy, scrollable task actions and calendar link accessible');
await popupWindow.evaluate(w=>w.setSize(460,550));const beforeActions=s.reminderMessage.id;const tasks=s.tasks;
await popup.locator('[data-id="'+tasks[0].id+'"][data-action="done"]').click();await popup.waitForFunction(()=>document.querySelectorAll('.reminder-row').length===2);
await popup.locator('[data-id="'+tasks[1].id+'"][data-action="snooze"]').click();await popup.waitForFunction(()=>document.querySelectorAll('.reminder-row').length===1);
await popup.locator('[data-id="'+tasks[2].id+'"][data-action="dismiss"]').click();await popup.waitForFunction(()=>document.querySelectorAll('.reminder-row').length===0);
s=await state(main);assert.equal(s.tasks.find(t=>t.id===tasks[0].id).done,true);assert(s.tasks.find(t=>t.id===tasks[1].id).snoozeUntil>Date.now()+590000);assert(s.history.every(h=>h.dismissed));assert.equal(s.reminderMessage.id,beforeActions);checks.push('complete, snooze and dismiss remain functional and do not consume extra copy');
await main.evaluate(()=>window.weeklight.settings({popup:false}));await popup.close();const oldQuote=s.reminderMessage.id;await main.evaluate(()=>window.weeklight.testReminder());s=await state(main);assert.notEqual(s.reminderMessage.id,oldQuote);assert(!app.windows().some(w=>w.url().endsWith('/reminder.html')));assert((await app.evaluate(()=>globalThis.__reminderNotifications)).at(-1).body.includes(s.reminderMessage.text));checks.push('notification-only mode still rotates copy without forcing the popup open');
assert.deepEqual(errors,[]);const result={passed:true,version:await app.evaluate(({app})=>app.getVersion()),catalogSize:messages.length,checks,rendererErrors:errors};await fs.writeFile(path.join(output,'reminder-desktop-tests.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}finally{if(app)await app.close();assert.equal(path.dirname(path.resolve(data)),path.join(root,'_work'));await fs.rm(data,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
